title: Sanskruti Rajankar
logo: /assets/headshot.JPG
description: I spend my days at the intersection of Python code, Tableau dashboards, and a fair amount of coffee.
show_downloads: false
theme: jekyll-theme-minimal
